name: Deploy MkDocs Documentation to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-mkdocs.yml'
      - 'requirements-docs.txt'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming your requirements file is at the root
          if [ -f requirements-docs.txt ]; then pip install -r requirements-docs.txt; fi
          # If it's in docs/
          # if [ -f docs/requirements-docs.txt ]; then pip install -r docs/requirements-docs.txt; fi
          # Or install directly:
          # pip install mkdocs mkdocs-material pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
